import sqlite3

# Creazione del database
conn = sqlite3.connect('../fornitori_data.db')
c = conn.cursor()
# Creazione della tabella
c.execute('''
CREATE TABLE IF NOT EXISTS fornitori_data (
    CODICE TEXT NOT NULL,
    DESCRIZIONE TEXT NOT NULL,
    FORNITORE TEXT NOT NULL,
    COMPOSIZIONE_CARTONE TEXT NOT NULL,
    PREZZO_VENDITA INTEGER NOT NULL,
    PREZZO_ACQUISTO INTEGER NOT NULL
)
''')

# Inserimento dei dati (solo se la tabella è vuota)
c.execute("INSERT into fornitori_data (CODICE, DESCRIZIONE, FORNITORE, COMPOSIZIONE_CARTONE, PREZZO_VENDITA, PREZZO_ACQUISTO) VALUES ('97', 'RICOTTA 1.5 KG', 'MARIO_LOSAPPIO', '2 PZ.', '7.75', '3.20')")
c.execute("INSERT into fornitori_data (CODICE, DESCRIZIONE, FORNITORE, COMPOSIZIONE_CARTONE, PREZZO_VENDITA, PREZZO_ACQUISTO) VALUES ('C109', 'MIELE MILLE/EVANGEL. 1 KG. (6)', 'PIZZA', '6 PZ.', '9.25', '6.50')")
c.execute("INSERT into fornitori_data (CODICE, DESCRIZIONE, FORNITORE, COMPOSIZIONE_CARTONE, PREZZO_VENDITA, PREZZO_ACQUISTO) VALUES ('C136', 'PANNA CREM PROF. 3 V. 1LT.(12)', 'BUONOMO', '12 PZ.', '3.10', '1.95')")
c.execute("INSERT into fornitori_data (CODICE, DESCRIZIONE, FORNITORE, COMPOSIZIONE_CARTONE, PREZZO_VENDITA, PREZZO_ACQUISTO) VALUES ('C84', 'PESTO BIFFI 1,5 KG. (1)', 'GIANCARLO', '1 PZ.', '20.90', '13.50')")
c.execute("INSERT into fornitori_data (CODICE, DESCRIZIONE, FORNITORE, COMPOSIZIONE_CARTONE, PREZZO_VENDITA, PREZZO_ACQUISTO) VALUES ('COTTO', 'MOTTA PROSC. COTTO 4 KG.+ (1)', 'PIZZA', '1 PZ.', '7.76', '4.20')")
c.execute("INSERT into fornitori_data (CODICE, DESCRIZIONE, FORNITORE, COMPOSIZIONE_CARTONE, PREZZO_VENDITA, PREZZO_ACQUISTO) VALUES ('G1', 'GRANA PADANO RET. 5 KG. +- (1)', 'SANGUEDOLCE', '1 PZ.', '12.88', '8.90')")
c.execute("INSERT into fornitori_data (CODICE, DESCRIZIONE, FORNITORE, COMPOSIZIONE_CARTONE, PREZZO_VENDITA, PREZZO_ACQUISTO) VALUES ('G10', 'RICOTTA SALATA GR. 400 +- (3)', 'SIGARETTE', '3 PZ.', '13.20', '7.50')")
c.execute("INSERT into fornitori_data (CODICE, DESCRIZIONE, FORNITORE, COMPOSIZIONE_CARTONE, PREZZO_VENDITA, PREZZO_ACQUISTO) VALUES ('G14', 'PECORINO ROM. PINNA 1 KG. (2)', 'STERLICCHIO', '2 PZ.', '19.98', '13.60')")
c.execute("INSERT into fornitori_data (CODICE, DESCRIZIONE, FORNITORE, COMPOSIZIONE_CARTONE, PREZZO_VENDITA, PREZZO_ACQUISTO) VALUES ('97', 'RICOTTA 1.5 KG. (2)', 'MARIO LOSAPPIO', '2 PZ.', '7.75', '3.20')")
c.execute("INSERT into fornitori_data (CODICE, DESCRIZIONE, FORNITORE, COMPOSIZIONE_CARTONE, PREZZO_VENDITA, PREZZO_ACQUISTO) VALUES ('C109', 'MIELE MILLE/EVANGEL. 1 KG. (6)', 'PIZZA', '6 PZ.', '9.25', '6.50')")
c.execute("INSERT into fornitori_data (CODICE, DESCRIZIONE, FORNITORE, COMPOSIZIONE_CARTONE, PREZZO_VENDITA, PREZZO_ACQUISTO) VALUES ('C136', 'PANNA CREM PROF. 3 V. 1LT.(12)', 'BUONOMO', '12 PZ.', '3.10', '1.95')")
c.execute("INSERT into fornitori_data (CODICE, DESCRIZIONE, FORNITORE, COMPOSIZIONE_CARTONE, PREZZO_VENDITA, PREZZO_ACQUISTO) VALUES ('C84', 'PESTO BIFFI 1,5 KG. (1)', 'GIANCARLO', '1 PZ.', '20.90', '13.50')")
c.execute("INSERT into fornitori_data (CODICE, DESCRIZIONE, FORNITORE, COMPOSIZIONE_CARTONE, PREZZO_VENDITA, PREZZO_ACQUISTO) VALUES ('COTTO', 'MOTTA PROSC. COTTO 4 KG.+ (1)', 'PIZZA', '1 PZ.', '7.76', '4.20')")
c.execute("INSERT into fornitori_data (CODICE, DESCRIZIONE, FORNITORE, COMPOSIZIONE_CARTONE, PREZZO_VENDITA, PREZZO_ACQUISTO) VALUES ('G1', 'GRANA PADANO RET. 5 KG. +- (1)', 'SANGUEDOLCE', '1 PZ.', '12.88', '8.90')")
c.execute("INSERT into fornitori_data (CODICE, DESCRIZIONE, FORNITORE, COMPOSIZIONE_CARTONE, PREZZO_VENDITA, PREZZO_ACQUISTO) VALUES ('G10', 'RICOTTA SALATA GR. 400 +- (3)', 'SIGARETTE', '3 PZ.', '13.20', '7.50')")
c.execute("INSERT into fornitori_data (CODICE, DESCRIZIONE, FORNITORE, COMPOSIZIONE_CARTONE, PREZZO_VENDITA, PREZZO_ACQUISTO) VALUES ('G14', 'PECORINO ROM. PINNA 1 KG. (2)', 'STERLICCHIO', '2 PZ.', '19.98', '13.60')")
conn.commit()
conn.close()